name: (CI) Push to Development

on:
  push:
    branches:
      - development  # Se ejecuta cuando hay un push en la rama development
  # pull_request:
  #   branches:
  #     - development  # Se ejecuta cuando hay un pull request hacia development

jobs:
  lint-test-pr:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linting
        run: |
          # Comando para ejecutar linting (ajusta según tu proyecto)
          echo "npm install"
          echo "npm run lint"
          
      - name: Run Tests
        run: |
          # Comando para ejecutar testing (ajusta según tu proyecto)
          echo "npm test"

      - name: Create Pull Request to Main
        if: success()  # Solo si el linting y testing pasaron
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
       
