name: (CI) Push to Development

on:
  push:
    branches:
      - development  # Se ejecuta cuando hay un push en la rama development

jobs:
  lint-test-pr:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development

      - name: Create Pull Request to Main
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
          PR_EXISTS: gh pr list --base main --head development --repo ${{ github.repository }} --json number | jq '.[].number'
        run: |
          echo PR_EXISTS=$(gh pr list --base main --head development --repo ${{ github.repository }} --json number  | jq '.[].number')
          echo $PR_EXISTS
          echo -z $PR_EXISTS
          # Crear pull request solo si no existe
          if [ -z "$PR_EXISTS" ]; then
            # Crear pull request solo si no existe
            gh pr create \
              --title "Merge development into main" \
              --body "Automatically created pull request to merge changes from development to main" \
              --base main \
              --head development
          else
            echo "Pull request from development to main already exists."
          fi

      